"""ProteinPool class for protein sequence pools."""

from typing import Literal

from typing_extensions import Self

from .pool import Pool
from .pool_mixins import ProteinMixin
from .types import Integral, Optional, Pool_type, beartype


@beartype
class ProteinPool(Pool, ProteinMixin):
    """Pool specialized for protein sequences.

    Inherits all generic operations from Pool and adds protein-specific
    operations via ProteinMixin. Overrides print_library() to support
    3-letter amino acid output format.
    """

    def __repr__(self) -> str:
        num_states_str = "None" if self.num_states is None else str(self.num_states)
        return f"ProteinPool(id={self._id}, name={self.name!r}, op={self.operation.name!r}, num_states={num_states_str})"

    def print_library(
        self,
        num_seqs: Optional[Integral] = None,
        num_cycles: Optional[Integral] = None,
        show_header: bool = True,
        show_state: bool = False,  # Changed default to False since state cols not generated by default
        show_name: bool = True,
        show_seq: bool = True,
        pad_names: bool = True,
        seed: Optional[Integral] = None,
        discard_null_seqs: bool = False,
        max_iterations: Optional[int] = None,
        min_acceptance_rate: Optional[float] = None,
        attempts_per_rate_assessment: int = 100,
        chars_per_aa: Literal[1, 3] = 1,
        aa_separator: str = " ",
    ) -> Self:
        """Print preview protein sequences from this pool; returns self for chaining.

        Parameters
        ----------
        num_seqs : Optional[Integral]
            Number of sequences to generate.
        num_cycles : Optional[Integral]
            Number of complete iterations through all states.
        show_header : bool, default=True
            Whether to show the pool header line.
        show_state : bool, default=True
            Whether to show the state column. Requires the pool
            to have been built with design cards that produce a state column;
            silently ignored otherwise.
        show_name : bool, default=True
            Whether to show the name column.
        show_seq : bool, default=True
            Whether to show the seq column.
        pad_names : bool, default=True
            Whether to pad names to align sequences.
        seed : Optional[Integral]
            Random seed for reproducibility.
        discard_null_seqs : bool, default=False
            If True, only show valid (non-null) sequences.
        max_iterations : Optional[int]
            Maximum iterations before stopping.
        min_acceptance_rate : Optional[float]
            Minimum fraction of sequences that must pass.
        attempts_per_rate_assessment : int, default=100
            Iterations between acceptance rate checks.
        chars_per_aa : Literal[1, 3], default=1
            Number of characters per amino acid. Use 1 for single-letter codes
            (e.g., "MAK") or 3 for three-letter codes (e.g., "Met Ala Lys").
        aa_separator : str, default=" "
            Separator between amino acids when chars_per_aa=3. Ignored when
            chars_per_aa=1.

        Returns
        -------
        ProteinPool
            Self, for method chaining.
        """
        gen_kwargs = {
            "seqs_only": False,
            "init_state": 0,
            "seed": seed,
            "_include_inline_styles": True,
            "discard_null_seqs": discard_null_seqs,
            "max_iterations": max_iterations,
            "min_acceptance_rate": min_acceptance_rate,
            "attempts_per_rate_assessment": attempts_per_rate_assessment,
        }
        if num_seqs is not None:
            gen_kwargs["num_seqs"] = num_seqs
        else:
            gen_kwargs["num_cycles"] = num_cycles if num_cycles is not None else 1
        df = self.generate_library(**gen_kwargs)
        has_name = show_name and "name" in df.columns and df["name"].notna().any()
        max_name_len = df["name"].str.len().max() if has_name and pad_names else 0

        if show_header:
            num_states_str = "None" if self.num_states is None else str(self.num_states)
            print(f"{self.name}: seq_length={self.seq_length}, num_states={num_states_str}")
            header_parts = []
            if show_state:
                header_parts.append("state")
            if has_name:
                header_parts.append(f"{'name':<{max_name_len}}" if pad_names else "name")
            if show_seq:
                header_parts.append("seq")
            if header_parts:
                print("  ".join(header_parts))

        state_col = f"{self.name}.state"
        # Disable show_state if the column doesn't exist
        if show_state and state_col not in df.columns:
            show_state = False
        for _, row in df.iterrows():
            row_parts = []
            if show_state:
                row_parts.append(f"{row[state_col]:5d}")
            if has_name:
                name = row["name"] if row["name"] is not None else ""
                if pad_names:
                    row_parts.append(f"{name:<{max_name_len}}")
                else:
                    row_parts.append(f"{name}")
            if show_seq:
                seq = row["seq"]
                if seq is None:
                    row_parts.append("None")
                else:
                    from .utils.style_utils import SeqStyle

                    inline_styles = row.get("_inline_styles", SeqStyle.empty(0))

                    # Convert to 3-letter if requested
                    if chars_per_aa == 3:
                        from .utils.protein_seq import (
                            map_style_positions_to_three_letter,
                            to_three_letter,
                        )

                        # Map style positions before converting sequence
                        if inline_styles is not None and inline_styles.style_list:
                            new_style_list = []
                            for spec, positions in inline_styles.style_list:
                                new_positions = map_style_positions_to_three_letter(
                                    positions, len(seq), separator=aa_separator
                                )
                                new_style_list.append((spec, new_positions))
                            three_letter_seq = to_three_letter(seq, separator=aa_separator)
                            inline_styles = SeqStyle(new_style_list, len(three_letter_seq))
                        seq = to_three_letter(seq, separator=aa_separator)

                    if inline_styles is not None:
                        seq = inline_styles.apply(seq)
                    row_parts.append(seq)
            print("  ".join(row_parts))
        print("")
        return self
