"""SeqSlice operation - slice SEQUENCES (string slicing)."""
from numbers import Real, Integral
from ..types import Union, Optional, Sequence, beartype
from ..pool import Pool


@beartype
def seq_slice(
    pool: Pool,
    key: Union[Integral, slice],
    name: Optional[str] = None,
    op_name: Optional[str] = None,
    iter_order: Optional[Real] = None,
    op_iter_order: Optional[Real] = None,
) -> Pool:
    """
    Create a Pool containing sequences that are slices of the input pool according to the specified key.

    Parameters
    ----------
    pool : Pool
        The Pool whose sequences will be sliced.
    key : Union[Integral, slice]
        Integer index or slice specifying the subsequence to extract from each sequence.
    name : Optional[str], default=None
        Name for the resulting Pool.
    op_name : Optional[str], default=None
        Name for the underlying slice Operation.
    iter_order : Real, default=0
        Iteration order priority for the resulting Pool.
    op_iter_order : Real, default=0
        Iteration order priority for the underlying Operation.

    Returns
    -------
    Pool
        A Pool containing sequences generated by applying the provided index or slice to each sequence in the input pool.
    """
    from .fixed import fixed_operation

    def seq_from_seqs_fn(seqs: list[str]) -> str:
        return seqs[0][key]

    def seq_length_from_pools_fn(pools: Sequence[Pool]) -> Optional[int]:
        parent_len = pools[0].seq_length
        if parent_len is None:
            return None
        if isinstance(key, Integral):
            return 1
        # For slice, compute length from slice params
        start, stop, step = key.indices(parent_len)
        return max(0, (stop - start + (step - 1 if step > 0 else step + 1)) // step)

    return fixed_operation(
        parents=[pool],
        seq_from_seqs_fn=seq_from_seqs_fn,
        seq_length_from_pools_fn=seq_length_from_pools_fn,
        name=name,
        op_name='seq_slice',
        iter_order=iter_order,
        op_iter_order=op_iter_order,
    )
