"""SliceSeq operation - slice SEQUENCES (string slicing)."""
from numbers import Real, Integral
from ..types import Union, Optional, Sequence, beartype
from ..pool import Pool


@beartype
def slice_seq(
    pool: Pool,
    key: Union[Integral, slice],
    iter_order: Optional[Real] = None,
    style: Optional[str] = None,
) -> Pool:
    """
    Create a Pool containing sequences that are slices of the input pool according to the specified key.

    Parameters
    ----------
    pool : Pool
        The Pool whose sequences will be sliced.
    key : Union[Integral, slice]
        Integer index or slice specifying the subsequence to extract from each sequence.
    iter_order : Optional[Real], default=None
        Iteration order priority for the Operation.
    style : Optional[str], default=None
        Style to apply to the resulting sliced sequences (e.g., 'red', 'blue bold').

    Returns
    -------
    Pool
        A Pool containing sequences generated by applying the provided index or slice to each sequence in the input pool.
    """
    from .fixed import fixed_operation

    def seq_from_seqs_fn(seqs: list[str]) -> str:
        return seqs[0][key]

    def seq_length_from_pool_lengths_fn(lengths: Sequence[Optional[int]]) -> Optional[int]:
        parent_len = lengths[0]
        if parent_len is None:
            return None
        if isinstance(key, Integral):
            return 1
        # For slice, compute length from slice params
        start, stop, step = key.indices(parent_len)
        return max(0, (stop - start + (step - 1 if step > 0 else step + 1)) // step)

    result_pool = fixed_operation(
        parent_pools=[pool],
        seq_from_seqs_fn=seq_from_seqs_fn,
        seq_length_from_pool_lengths_fn=seq_length_from_pool_lengths_fn,
        iter_order=iter_order,
        _factory_name='slice_seq',
    )
    
    # Apply style if specified
    if style is not None:
        from .style import stylize
        result_pool = stylize(result_pool, style=style)
    
    return result_pool
