"""SeqSlice operation - slice SEQUENCES (string slicing)."""
from numbers import Real
import statecounter as sc
from ..types import Union, Optional, Sequence, Integral, Real, beartype
from ..operation import Operation
from ..pool import Pool
import numpy as np


@beartype
class SeqSliceOp(Operation):
    """Slice sequences using Python slice notation."""
    factory_name = "seq_slice"
    design_card_keys = []
    
    def __init__(
        self,
        parent_pool: Pool,
        key: Union[Integral, slice],
        name: Optional[str] = None,
        iter_order: Real = 0,
    ) -> None:
        """Initialize SeqSliceOp."""
        self.key = key
        # Compute seq_length from slice params and parent length
        parent_len = parent_pool.seq_length
        if parent_len is not None:
            if isinstance(key, Integral):
                seq_length = 1
            else:
                start, stop, step = key.indices(parent_len)
                seq_length = max(0, (stop - start + (step - 1 if step > 0 else step + 1)) // step)
        else:
            seq_length = None
        super().__init__(
            parent_pools=[parent_pool],
            num_states=1,
            seq_length=seq_length,
            name=name,
            iter_order=iter_order,
        )
    
    def build_pool_counter(
        self,
        parent_pools: Sequence[Pool],
    ) -> sc.Counter:
        """Return parent counter directly (no state added)."""
        return parent_pools[0].counter
    
    def compute_design_card(
        self,
        parent_seqs: list[str],
        rng: Optional[np.random.Generator] = None,
    ) -> dict:
        """Return empty design card (no design decisions)."""
        return {}
    
    def compute_seq_from_card(
        self,
        parent_seqs: list[str],
        card: dict,
    ) -> dict:
        """Apply slice to parent sequence."""
        seq = parent_seqs[0]
        result = seq[self.key]
        return {'seq_0': result}
    
    def _get_copy_params(self) -> dict:
        """Return parameters needed to create a copy of this operation."""
        return {
            'parent_pool': self.parent_pools[0],
            'key': self.key,
            'name': None,
            'iter_order': self.iter_order,
        }


@beartype
def seq_slice(
    pool: Pool,
    key: Union[Integral, slice],
    name: Optional[str] = None,
    op_name: Optional[str] = None,
    iter_order: Real = 0,
    op_iter_order: Real = 0,
) -> Pool:
    """
    Create a Pool containing sequences that are slices of the input pool according to the specified key.

    Parameters
    ----------
    pool : Pool
        The Pool whose sequences will be sliced.
    key : Union[Integral, slice]
        Integer index or slice specifying the subsequence to extract from each sequence.
    name : Optional[str], default=None
        Name for the resulting Pool.
    op_name : Optional[str], default=None
        Name for the underlying slice Operation.
    iter_order : Real, default=0
        Iteration order priority for the resulting Pool.
    op_iter_order : Real, default=0
        Iteration order priority for the underlying Operation.

    Returns
    -------
    Pool
        A Pool containing sequences generated by applying the provided index or slice to each sequence in the input pool.
    """
    op = SeqSliceOp(pool, key=key, name=op_name, iter_order=op_iter_order)
    result_pool = Pool(operation=op, iter_order=iter_order, name=name)
    return result_pool
